
fail_fast: true

repos:
  - repo: local
    hooks:

      # 1)
      - id: remove-unused-imports 
        name: "Ruff checkout for unused import statements"
        language: system
        entry: bash -lc 'ruff check --select F401 noyse.ipynb'
        pass_filenames: false

      # 1) Convert notebook to script and stage it
      - id: jupytext
        name: "Jupytext: ipynb -> py (noyse)"
        language: system
        entry: bash -lc 'jupytext --to py noyse.ipynb'
        pass_filenames: false

